From: Takashi Iwai <tiwai@suse.de>
Subject: [PATCH] usbcore: Fix wrong device in an error message in hub_port_connect()
Patch-mainline: v3.17-rc3
Git-commit: dd5f5006d1035547559c8a90781a7e249787a7a2
References: bnc#892457

The commit [5ee0f803cc3a: usbcore: don't log on consecutive debounce
failures of the same port] added the check of the reliable port, but
it also replaced the device argument to dev_err() wrongly, which leads
to a NULL dereference.

This patch restores the right device, port_dev->dev.

[The fix suggested by Hannes]

Fixes: 5ee0f803cc3a ('usbcore: don't log on consecutive debounce failures of the same port')
Reported-by: Hannes Reinecke <hare@suse.com>
Signed-off-by: Takashi Iwai <tiwai@suse.de>

---
 drivers/usb/core/hub.c | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

Index: linux-3.12-SLE12/drivers/usb/core/hub.c
===================================================================
--- linux-3.12-SLE12.orig/drivers/usb/core/hub.c
+++ linux-3.12-SLE12/drivers/usb/core/hub.c
@@ -4633,7 +4633,7 @@ static void hub_port_connect(struct usb_
 			if (status != -ENODEV &&
 				port1 != unreliable_port &&
 				printk_ratelimit())
-				dev_err(&udev->dev, "connect-debounce failed, port %d disabled\n",
+				dev_err(&port_dev->dev, "connect-debounce failed, port %d disabled\n",
 					port1);
 
 			portstatus &= ~USB_PORT_STAT_CONNECTION;
