From: Takashi Iwai <tiwai@suse.de>
Subject: [PATCH] usbcore: Fix wrong device in an error message in hub_port_connect()
Patch-mainline: v3.17-rc3
Git-commit: dd5f5006d1035547559c8a90781a7e249787a7a2
References: bnc#892457

The commit [5ee0f803cc3a: usbcore: don't log on consecutive debounce
failures of the same port] added the check of the reliable port, but
it also replaced the device argument to dev_err() wrongly, which leads
to a NULL dereference.

This patch restores the right device, port_dev->dev.

[The fix suggested by Hannes]

Fixes: 5ee0f803cc3a ('usbcore: don't log on consecutive debounce failures of the same port')
Reported-by: Hannes Reinecke <hare@suse.com>
Signed-off-by: Takashi Iwai <tiwai@suse.de>

---
 drivers/usb/core/hub.c | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/drivers/usb/core/hub.c b/drivers/usb/core/hub.c
index 8a4dcbc7a75f..22635590860c 100644
--- a/drivers/usb/core/hub.c
+++ b/drivers/usb/core/hub.c
@@ -4631,7 +4631,7 @@ static void hub_port_connect(struct usb_hub *hub, int port1, u16 portstatus,
 			if (status != -ENODEV &&
 				port1 != unreliable_port &&
 				printk_ratelimit())
-				dev_err(&udev->dev, "connect-debounce failed, port %d disabled\n",
+				dev_err(&port_dev->dev, "connect-debounce failed, port %d disabled\n",
 					port1);
 
 			portstatus &= ~USB_PORT_STAT_CONNECTION;
-- 
2.0.4

